apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.pv.accessModes }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.pv.path }}
