apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      nodePort: {{ .Values.service.externalPort }}
  type: NodePort
